### ISSUE TITLE
add the repository before trying to install

### ISSUE THREAD

**Issue by hutchic** [le9i0nx/ansible-syncthing#3]
If you don't add the repository and repository key this playbook doesn't do much.

For example stock ubuntu 14.04 running ansible `2.0.1.0`

```
TASK [syncthing : install] *****************************************************
included: /etc/ansible/roles/syncthing/tasks/install.yml for localhost

TASK [syncthing : deb based distros] *******************************************
included: /etc/ansible/roles/syncthing/tasks/os_deb.yml for localhost

TASK [syncthing : install required packages] ***********************************
failed: [localhost] => (item=[u'syncthing', u'syncthing-inotify', u'python-httplib2']) => {"failed": true, "item": ["syncthing", "syncthing-inotify", "python-httplib2"], "msg": "No package matching 'syncthing' is available"}
    to retry, use: --limit @playbook.retry
```

**Comment by le9i0nx** [comment]
Hi
https://github.com/le9i0nx/ansible-root/blob/master/service/syncthing.yml#L25-L30

Indicated in the documentation link "playbook"
https://github.com/le9i0nx/ansible-syncthing/blob/master/README.md

**Comment by le9i0nx** [comment]
I corrected role #4
response if performed successfully

**Comment by hutchic** [comment]
sorry been busy I'll try and verify this weekend

**Comment by hutchic** [comment]
can confirm this works :+1: 

only issue I ran into was syncthing launched on port `42199` while you're wait_for is on port `8384`. Still investigating I may have a PR for you at some point
